name: Android Fastlane with Firebase App Distribution WorkFlow

on:
  push:
    - master

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo codeass
      uses: actions/checkout@v2

    - name: Set up JDK11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: install flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3.4"
        bundler=cache: true
        working-directory : android

    - name: build and Distrubtue App
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN}}
      run:
        bundle exec fastlane android firebase_distribution
      working-directory: android
